### ISSUE TITLE
Error __buffer_arg_is_not_array

### ISSUE THREAD

**Issue by mingodad** [servalproject/serval-dna#115]
Hello !
I'm trying to compile on ubuntu 14.04 with gcc 6 and I'm getting this erros:

```
make -j 4 
SERVALD CC http_server.c
SERVALD CC rhizome_bundle.c
SERVALD CC rhizome_direct_cli.c
SERVALD CC rhizome_fetch.c
In file included from uuid.h:26:0,
                 from rhizome.h:31,
                 from rhizome_direct_cli.c:23:
rhizome_direct_cli.c: In function ‘rhizome_sync_with_peers’:
strbuf.h:303:124: error: call to ‘__buffer_arg_is_not_array’ declared with attribute error: argument to strbuf_local_buf() must be an array not a pointer
 #   define strbuf_local_buf(buf) strbuf_local((char*)(buf), (sizeof(buf) == __builtin_object_size(buf, 1)) ? sizeof(buf) : __buffer_arg_is_not_array())
                                                                                                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
strbuf.h:264:87: note: in definition of macro ‘strbuf_local’
 #define strbuf_local(buf,len) __strbuf_init_chk(alloca(SIZEOF_STRBUF), (char*)(buf), (len), __builtin_object_size((buf), 1))
                                                                                       ^~~
rhizome_direct_cli.c:60:16: note: in expansion of macro ‘strbuf_local_buf’
     strbuf h = strbuf_local_buf(state->host);
                ^~~~~~~~~~~~~~~~
make: *** [objs_servald/rhizome_direct_cli.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from instance.h:26:0,
                 from serval.h:128,
                 from rhizome_fetch.c:23:
```

Cheers !

**Comment by lakeman** [comment]
We might be triggering the same condition as this test case;
https://android.googlesource.com/toolchain/gcc/+/32fce3edda831e36ee484406c39dffbe0230f257/gcc-4.8/gcc/testsuite/gcc.dg/builtin-object-size-6.c#55

But I don't know why that test is expected to return -1. It makes no sense
to me.

**Comment by kbmulligan** [comment]
I think you can close this due to this commit:
https://github.com/servalproject/serval-dna/commit/f83b15d251aeffce9f015f64a1668bc63fea497c#diff-198e52d1482d46a3ffe7817dce7ec910
